### ISSUE TITLE
Add ./Metadata/Coverage mapping

### ISSUE THREAD

**Issue by airnst** [gfbio/bioschemas.org_interest_group#10]
#### Description
_abcd:Dataset/Dataset/Metadata/Coverage_ of a dataset describes, for example, taxonomic or geographic terms and descriptions of the project in which the dataset is located. These terms can be mapped to the [schema:keywords](https://schema.org/keywords) property which can hold a list of [DefinedTerms](https://schema.org/DefinedTerm) or strings. Also, the example file must be extended. Example values are "1995-1996" or "Boston, MA".

#### Files
[XML file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/example_files/HoffmannPlantsV3.xml)
[XSLT file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/abcd2bioschemas-xml.xslt)

#### Tasks
- [x] Extend example XML file.
- [x] Update XSLT file.
- [x] Test if coverage information is mapped correctly.
