### ISSUE TITLE
Add ./IPRStatements/Acknowledgements mapping

### ISSUE THREAD

**Issue by airnst** [gfbio/bioschemas.org_interest_group#11]
#### Description
At times, datasets credit someone or something in _abcd:Dataset/Dataset/IPRStatements/Acknowledgements/Acknowledgement_. This information is described by _Text_ and optionally both _Details_ and _URI_. Currently, there is only the [schema:creditText](https://schema.org/creditText) property that describes something similar. Unfortunately, its domain are plain strings. So, it cannot be mapped without altering or losing information. 

#### Open questions
Three workaround ideas:
1. Assign only _Text_ to _creditText_,
2. combine _Text_, _Details_, and _URI_ in one _creditText_ (possibly with separators), or
3. assign _Text_, _Details_, and _URI_ separated in a list of text strings to _creditText_.

These ideas are far from elegant solutions. In fact, it would be better if creditText is renamed to credit, which is a property with a domain containing CreativeWork as type. In this way, any information could be properly mapped.

#### Files
[XML file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/example_files/HoffmannPlantsV3.xml)
[XSLT file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/abcd2bioschemas-xml.xslt)

#### Tasks
- [ ] Discuss open questions.
- [ ] Extend example XML file.
- [ ] Update XSLT file.
- [ ] Test if coverage information is mapped correctly.
