### ISSUE TITLE
Extend mapping to spatialCoverage

### ISSUE THREAD

**Issue by airnst** [gfbio/bioschemas.org_interest_group#12]
#### Description
In the dataset, some locality information is already mapped to schema:[spatialCoverage](https://schema.org/spatialCoverage):[Place](https://schema.org/Place) properties, see
- ./Gathering/Country/Name &rarr; Place:name
- ./Gathering/Country/ISO3166Code &rarr; Place:identifier
- ./Gathering/SiteCoordinateSets/SiteCoordinates/CoordinatesLatLong/LongitudeDecimal &rarr; Place:geo:GeoCoordinates:longitude
- ./Gathering/SiteCoordinateSets/SiteCoordinates/CoordinatesLatLong/LatitudeDecimal &rarr; Place:geo:GeoCoordinates:latitude

The following information can be mapped as well:
- ./Gathering/LocalityText &rarr; Place:description
- ./Gathering/NamedAreas/NamedArea/AreaName &rarr; Place:keywords
- ./Gathering/NamedAreas/NamedArea/AreaClass &rarr; Place:additionalType
- ./Gathering/Altitude &rarr; Place:geo:GeoCoordinates:elevation
- ./Gathering/SiteCoordinateSets/SiteCoordinates/CoordinatesLatLong/SpatialDatum &rarr; Place:geo:GeoCoordinates:additionalType

For testing, some units in the example XML must be extended by corresponding location information.

#### Open questions
Altitude is much more complex to map as it can be a MeasurementOrFactAtomised and thus can be a range with or without different units used. However, altitude information can be used to create a PropertyValue _Elevation_ with a _minValue_ and a _maxValue_ that enables filtering datasets by elevation. 

#### Files
[XML file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/example_files/HoffmannPlantsV3.xml)
[XSLT file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/abcd2bioschemas-xml.xslt)

#### Tasks
- [x] Extend example XML file.
- [x] Update XSLT file.
- [x] Create follow-up ticket.
- [x] Test if spatialCoverage information is mapped correctly.

**Comment by airnst** [comment]
Many thanks for providing the example files, @snsb-seifert!
