### ISSUE TITLE
Test litho- and chronostratigraphic term mapping

### ISSUE THREAD

**Issue by airnst** [gfbio/bioschemas.org_interest_group#13]
#### Description
A mapping of both _./Gathering/Stratigraphy/ChronostratigraphicTerms/ChronostratigraphicTerm/Term_ and _/Gathering/Stratigraphy/LithostratigraphicTerms/LithostratigraphicTerm/Term_ to the [schema:keywords](https://schema.org/keywords) property of [schema:Dataset](https://schema.org/Dataset) has already been implemented. For testing, some units in the example XML must be extended by these terms.

#### Files
[XML file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/example_files/HoffmannPlantsV3.xml)

#### Tasks
- [x] Extend example XML file.
- [x] Update XSLT file in case of bugs.
- [x] Test if terms are mapped correctly.

**Comment by airnst** [comment]
Thanks a lot, @snsb-seifert! I'm gonna integrate your example dataset in the
