### ISSUE TITLE
Add ./MultiMediaObjects mapping

### ISSUE THREAD

**Issue by airnst** [gfbio/bioschemas.org_interest_group#14]
#### Description
Information in _./Units/Unit/MultiMediaObjects/MultiMediaObject_ can be mapped as a list to the [schema:associatedMedia](https://schema.org/associatedMedia) property as follows:
- ./MultiMediaObject/FileURI &rarr; MediaObject:contentUrl
- ./MultiMediaObject/ProductURI &rarr; MediaObject:mainEntityOfPage
- ./MultiMediaObject/Format &rarr; MediaObject:encodingFormat
- ./MultiMediaObject/IPR/Licenses/License/Text &rarr; MediaObject:license:CreativeWork:name
- ./MultiMediaObject/IPR/Licenses/License/Details &rarr; MediaObject:license:CreativeWork:description
- ./MultiMediaObject/IPR/Licenses/License/URI &rarr; MediaObject:license:CreativeWork:uri
- ./MultiMediaObject/Creator &rarr; MediaObject:creator

#### Files
[XML file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/example_files/HoffmannPlantsV3.xml)
[XSLT file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/abcd2bioschemas-xml.xslt)

#### Tasks
- [ ] Extend example XML file.
- [ ] Update XSLT file.
- [ ] Test if multimedia information is mapped correctly.
