### ISSUE TITLE
Add ./KindOfUnit mapping

### ISSUE THREAD

**Issue by airnst** [gfbio/bioschemas.org_interest_group#16]
#### Description
_abcd:Dataset/Dataset/Units/Unit/KindOfUnit_ describes the material class a certain unit represents, for example, "herbarium sheet", "legs" or "whole organism". These classes can be mapped to [schema:additionalType](https://schema.org/additionalType) as simple strings.

#### Files
[XML file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/example_files/HoffmannPlantsV3.xml)
[XSLT file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/abcd2bioschemas-xml.xslt)

#### Tasks
- [x] Extend example XML file.
- [x] Update XSLT file.
- [x] Test if type information is mapped correctly.
