### ISSUE TITLE
Add altitude mapping

### ISSUE THREAD

**Issue by airnst** [gfbio/bioschemas.org_interest_group#17]
#### Description
Altitude can be mapped on [schema:variableMeasured](https://schema.org/variableMeasured) with a [schema:PropertyValue](https://schema.org/PropertyValue). In a PropertyValue, we can specify [schema:elevation](https://schema.org/elevation) as _propertyID_, "Elevation" as _name_ and _value_, _minValue_ and _maxValue_. The latter allows mapping of ranges of all elevations in datasets and enables filtering for those.

Related to ticket [#12].

#### Files
[XML file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/example_files/HoffmannPlantsV3.xml)
[XSLT file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/abcd2bioschemas-xml.xslt)

#### Tasks
- [ ] Extend example XML file.
- [ ] Update XSLT file.
- [ ] Test if variableMeasured information is mapped correctly.
