### ISSUE TITLE
Extend unit-level information to keywords mapping

### ISSUE THREAD

**Issue by airnst** [gfbio/bioschemas.org_interest_group#19]
#### Description
Unit-level information about both _abcd:Biotope_ and _abcd:ProjectTitle_ can be mapped to _schema:keywords_. 

#### Files
[XML file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/example_files/HoffmannPlantsV3.xml)
[XSLT file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/abcd2bioschemas-xml.xslt)

#### Tasks
- [x] Extend example XML file.
- [x] Update XSLT file.
- [x] Test if keywords are complete.
