### ISSUE TITLE
Add ./Unit/RecordURI mapping

### ISSUE THREAD

**Issue by airnst** [gfbio/bioschemas.org_interest_group#20]
#### Description
Unit-level record URIs can be a attribute of datasets and would enable filtering by this information. _abcd:RecordURI_ can be mapped to [schema:url](https://schema.org/url) of an [schema:BioSample](https://bioschemas.org/profiles/BioSample/0.1-DRAFT-2019_11_12)/CreativeWork entity which is referenced by [schema:hasPart](https://schema.org/hasPart) of the dataset.

#### Files
[XML file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/example_files/HoffmannPlantsV3.xml)
[XSLT file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/abcd2bioschemas-xml.xslt)

#### Open questions
Discuss if it is beneficiary for search to have many BioSamples/CreativeWorks in hasPart. Why not map other unit-level information to them?

#### Tasks
- [ ] Extend example XML file.
- [ ] Update XSLT file.
- [ ] Test if record URIs are mapped correctly.

**Comment by snsb-seifert** [comment]
abcd:RecordURI might not be an URL.
