### ISSUE TITLE
Add ./Unit/SourceReference mapping

### ISSUE THREAD

**Issue by airnst** [gfbio/bioschemas.org_interest_group#21]
#### Description
Unit records can be based on a publication as source that is referenced in _abcd:./Unit/SourceReference_. To enable filtering for datasets containing a given reference, these references can be assigned to the [schema:citation](https://schema.org/citation) property as a [schema:CreativeWork](https://schema.org/CreativeWork). 

#### Files
[XML file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/example_files/HoffmannPlantsV3.xml)
[XSLT file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/abcd2bioschemas-xml.xslt)

#### Tasks
- [ ] Extend example XML file.
- [ ] Update XSLT file.
- [ ] Test if references are mapped correctly.
