### ISSUE TITLE
Add ./Unit/UnitReferences mapping

### ISSUE THREAD

**Issue by airnst** [gfbio/bioschemas.org_interest_group#26]
#### Description
In addition to the publications upon which the units in the dataset are based, the information in the _abcd:UnitReferences_ element can be used to make it possible to filter datasets by publications that cite them. Since [schema:citation](https://schema.org/citation) represents the inverse property of this requirement, it may be used by additionally applying the JSON-LD keyword _@reverse_.

#### Files
[XML file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/example_files/HoffmannPlantsV3.xml)
[XSLT file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/abcd2bioschemas-xml.xslt)

#### Tasks
- [ ] Extend example XML file.
- [ ] Update XSLT file.
- [ ] Test if citing publications are mapped correctly.
