### ISSUE TITLE
Add mapping of various unit IDs

### ISSUE THREAD

**Issue by airnst** [gfbio/bioschemas.org_interest_group#27]
#### Description
The search for datasets that contain a specific record ID requires the mapping of IDs at unit level. Mapping them on [schema:identifier](https://schema.org/identifier) of [bioschemas:BioSample](https://bioschemas.org/profiles/BioSample/0.1-DRAFT-2019_11_12) entities in schema:about of a [schema:Dataset](https://schema.org/Dataset) is a suitable approach, as IDs are thus accessible in a relatively flat structure, which facilitates browsing datasets. Values of the following ABCD elements are mapped to [schema:identifier](https://schema.org/identifier):
- _/DataSets/DataSet/Units/Unit/SourceInstitutionID_
- _/DataSets/DataSet/Units/Unit/SourceID_
- _/DataSets/DataSet/Units/Unit/UnitID_
- _/DataSets/DataSet/Units/Unit/UnitIDNumeric_
- _/DataSets/DataSet/Units/Unit/UnitGUID_

This issue is related to [#20].

#### Files
[XML file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/example_files/HoffmannPlantsV3.xml)
[XSLT file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/abcd2bioschemas-xml.xslt)

#### Tasks
- [ ] Extend example XML file.
- [ ] Update XSLT file.
- [ ] Test if identifier are mapped correctly.
