### ISSUE TITLE
Add ./GatheringAgent mapping

### ISSUE THREAD

**Issue by airnst** [gfbio/bioschemas.org_interest_group#28]
#### Description
In order to enable the search for datasets that include units with a given _abcd./GatheringAgent_, it is necessary to map this person information. The dataset property [schema:contributor](https://schema.org/contributor) with its range [schema:Person](https://schema.org/Person) and [schema:Organization](https://schema.org/Organization) is ideal for this.

#### Files
[XML file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/example_files/HoffmannPlantsV3.xml)
[XSLT file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/abcd2bioschemas-xml.xslt)

#### Tasks
- [x] Extend example XML file.
- [x] Update XSLT file.
- [x] Test if Gathering Agent is mapped correctly.
