### ISSUE TITLE
Add ./CollectorsFieldNumber mapping

### ISSUE THREAD

**Issue by airnst** [gfbio/bioschemas.org_interest_group#29]
#### Description
Units may hold an identifying _abcd:./CollectorsFieldNumber_, which is assigned by the collector and can therefore be of interest for search purposes. Such an identifier can be mapped directly to the [schema:identifier](https://schema.org/identifier) property of a [bioschemas:BioSample](https://bioschemas.org/profiles/BioSample/0.1-DRAFT-2019_11_12) that is assigned to the datasets [schema:about](https://schema.org/citation) property.

#### Files
[XML file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/example_files/HoffmannPlantsV3.xml)
[XSLT file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/abcd2bioschemas-xml.xslt)

#### Tasks
- [ ] Extend example XML file.
- [ ] Update XSLT file.
- [ ] Test if collector field number is correctly mapped on its corresponding gathering agent.
