### ISSUE TITLE
Add ./DirectAccessURI and ./IconURI mapping

### ISSUE THREAD

**Issue by airnst** [gfbio/bioschemas.org_interest_group#4]
#### Description
While _abcd:DirectAccessURI_ can be mapped to _Dataset:distribution_ (type: [DataDownload](https://schema.org/DataDownload), _abcd:IconURI_ can be mapped to _Dataset:image_ (type: URL in case of included _http_, or [schema:identifier](https://schema.org/identifier) of a [schema:ImageObject](https://schema.org/ImageObject) in case of non-URL identifier). In addition, the example XML file must be extended by the respective information.

#### Files
[XSLT file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/abcd2bioschemas-xml.xslt)
[XML file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/example_files/HoffmannPlantsV3.xml)

#### Open questions
1. _abcd:DirectAccessURI_ may refer to a website query form instead of a direct download, which would clash with the definition of Dataset:distribution. It should be discussed whether this case could cause subsequent problems.

#### Tasks
- [x] Update XML file.
- [x] Update XSLT file.
- [x] Test if mapping works as defined.
- [x] Resolve open questions.

#### Solution
For _abcd:DirectAccessURI_, if the URL contains a file format (currently only ZIP), it is mapped to _DataDownload:contentURL_ with additional information in _DataDownload:encodingFormat_. If not, the URL is simply assigned to _DataDownload:url_.

**Comment by airnst** [comment]
Concerning the open question: In case the link contains a file extension such as _.zip_, it can be used as _schema:distribution_ value. The current implementation already contains this checking, but must be adapted so that no distribution is added if the link does not contain a format specification.

**Comment by airnst** [comment]
A solution has been added for the problem if icon URIs are not URLs. See ticket description.
