### ISSUE TITLE
Add ./Owner/Roles mapping

### ISSUE THREAD

**Issue by airnst** [gfbio/bioschemas.org_interest_group#5]
#### Description 
A dataset may contain information about the role(s) of its owner (e.g. database administrator). Owners are currently mapped to _Dataset:author_ with the value type of either
1. a [Person ](https://schema.org/Person) (with an affiliated organization) or,
2. an [Organization ](https://schema.org/Organization) only. 

Multiple roles can be included for one owner. Any of these roles should be mapped to _Dataset:author:jobTitle_ (property of type [Person ](https://schema.org/Person)) if the first case applies. Further, the XML example file must be extended by a proper example.

#### Files
[XSLT file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/abcd2bioschemas-xml.xslt)
[XML file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/example_files/HoffmannPlantsV3.xml)

#### Tasks
- [x] Update XML file (must contain both a person and an organization owner).
- [x] Update XSLT file.
- [x] Test if owner roles are correctly mapped.
