### ISSUE TITLE
Add ./IPRStatements/Citations mapping

### ISSUE THREAD

**Issue by airnst** [gfbio/bioschemas.org_interest_group#6]
#### Description
Citation requirements of a dataset are documented in _abcd:Citations_ (Text, Details, URI). A proper [schema.org](schema.org) property for this information is _Dataset:usageInfo_ which points to a _CreativeWork_ object. As _abcd:TermsOfUseStatements_ are likewise mapped to _usageInfo_, this must be taken into account (i.e. using lists) as well as that multiple license might be specified. Also, the XML example file must be extended.

#### Files
[XML file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/example_files/HoffmannPlantsV3.xml)
[XSLT file](https://github.com/gfbio/bioschemas.org_interest_group/blob/main/transformations/abcd2bioschemas/abcd2bioschemas-xml.xslt)

#### Tasks
- [x] Extend example XML file.
- [x] Update XSLT file.
- [x] Test if citation information is mapped correctly.
